version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shift-planner-db
    environment:
      POSTGRES_USER: shift_planner
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shift_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shift_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
